[font]
# normal = { family = "Font Awesome 6 Free", style = "Regular" }
size = 12
[cursor]
style = { shape = "Underline" }
# unfocused_hollow = false
[window]
# margin = 10
dynamic_padding = true
dynamic_title = true
decorations_theme_variant = "Dark"
# padding = { x = 0, y = 0 }
#decorations = buttonless
decorations =  "Buttonless"
startup_mode = "SimpleFullscreen"
[scrolling]
history = 1000
# save_to_clipboard = true
[terminal]
osc52 = "CopyPaste"

