require("plugins.prettier.init")
require("plugins.packer-config.init")
require("plugins.keymap-config.init")
require("plugins.lsp.init")
require("plugins.options.init")
require("plugins.telescope.init")
require("plugins.telescope-file-browser.init")
require("plugins.lualine.init")
require("plugins.notifity.init")
require("plugins.gitgutter.init")

