return {

	lsp = {
		-- enable = true,
		-- neodev = true,

		ensure_installed = {
			"clangd",
			"cssls",
			"css-lsp",
			"emmet-ls",
			"eslint",
			"html",
			"jdtls",
			"jq",
			"jsonls",
			"json-lsp",
			"lua_ls",
			"markdownlint",
			"pyright",
			"rust_analyzer",
			"selene",
			"shellcheck",
			"shfmt",
			"sqlls",
			"standardjs",
			"stylua",
			"tailwindcss",
			"tailwindcss-language-server",
			"tsserver",
			"typescript-language-server",
			"vimls",
			"yamlls",
		},

		capabilities = require("cmp_nvim_lsp").default_capabilities(vim.lsp.protocol.make_client_capabilities()),
		on_attach = require("lsp-format").on_attach,
		flags = require("configs.lsp.flags"),
	},
	treesitter = {
		ensure_installed = {
			"bash",
			"css",
			"go",
			"gomod",
			"html",
			"http",
			"javascript",
			"jsdoc",
			"json",
			"lua",
			"luadoc",
			"markdown",
			"markdown_inline",
			"nix",
			"org",
			"php",
			"phpdoc",
			"python",
			"query",
			"regex",
			"rust",
			"sql",
			"svelte",
			"typescript",
			"vim",
			"yaml",
		},
	},
	default_options = function(options)
		return vim.tbl_deep_extend("force", {
			on_attach = require("configs.lsp.attach"),
			flags = require("configs.lsp.flags"),
		}, options)
	end,
}
